openapi: 3.0.1
info:
    title: HealthGod Plugin
    description: A plugin that allows the user to create and manage a TODO list using ChatGPT.
    version: 'v1'
servers:
    - url: https://healthgod.xyz
paths:
    /api/ask-question:
        post:
            operationId: askQuestion
            summary: ask for medical advice
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/addQuestionRequest'
            responses:
                '200':
                    description: OK
components:
    schemas:
        addQuestionRequest:
            type: object
            required:
                - question
            properties:
                todo:
                    type: string
                    description: The question you need advice on.
                    required: true
