openapi: 3.0.1
info:
    title: HealthGod Plugin
    description: A plugin that allows the user to ask for personalised medical advice using ChatGPT.
    version: 'v1'
servers:
    - url: https://healthgod.xyz
paths:
    /api/ask-question:
        post:
            operationId: askQuestion
            summary: ask for medical advice
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/addQuestionRequest'
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/questionResponse'
components:
    schemas:
        addQuestionRequest:
            type: object
            required:
                - question
            properties:
                question:
                    type: string
                    description: The question you need advice on.
                    required: true

        questionResponse:
            type: object
            properties:
                advice:
                    type: string
                    description: advice from healthGod
